# ndarray 연산

In [1]:
import numpy as np

## 기본 연산

In [ ]:
# reshape(row_num, col_num) => !!!element 개수 맞게 해야함!!!
arr_a = np.arange(1,10).reshape(3,3)
arr_b = np.full_like(arr_a, 7) # full_like(array, value): array 모양 복제해서 value 다 거기 넣어줌

print(arr_a)
print(arr_b)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[7 7 7]
 [7 7 7]
 [7 7 7]]


In [ ]:
# 덧셈
print(arr_a + arr_b)

print(np.add(arr_a, arr_b))

[[ 8  9 10]
 [11 12 13]
 [14 15 16]]
[[ 8  9 10]
 [11 12 13]
 [14 15 16]]


In [ ]:
# 뺄셈
print(arr_a - arr_b)

print(np.subtract(arr_a, arr_b))

[[-6 -5 -4]
 [-3 -2 -1]
 [ 0  1  2]]
[[-6 -5 -4]
 [-3 -2 -1]
 [ 0  1  2]]


In [ ]:
# 곱셈: 같은 위치에 있는 놈끼리 곱함
print(arr_a * arr_b)

print(np.multiply(arr_a, arr_b))

[[ 7 14 21]
 [28 35 42]
 [49 56 63]]
[[ 7 14 21]
 [28 35 42]
 [49 56 63]]


In [ ]:
# 나눗셈
print(arr_a / arr_b)

print(np.divide(arr_a, arr_b))

[[0.14285714 0.28571429 0.42857143]
 [0.57142857 0.71428571 0.85714286]
 [1.         1.14285714 1.28571429]]
[[0.14285714 0.28571429 0.42857143]
 [0.57142857 0.71428571 0.85714286]
 [1.         1.14285714 1.28571429]]


## 특수연산

In [ ]:
# 1. quotient 몫 연산
print(arr_a // arr_b)

print(np.floor_divide(arr_a, arr_b))

[[0 0 0]
 [0 0 0]
 [1 1 1]]
[[0 0 0]
 [0 0 0]
 [1 1 1]]


In [ ]:
# 2. modulo
print(arr_a % arr_b)

print(np.mod(arr_a, arr_b))

[[1 2 3]
 [4 5 6]
 [0 1 2]]
[[1 2 3]
 [4 5 6]
 [0 1 2]]


In [29]:
# 3. square
print(arr_a ** arr_b)

print(np.power(arr_a, arr_b))

print(np.square(arr_a)) # 하나의 matrix에 대해서 제곱하는 것
print(np.sqrt(arr_a)) # 하나의 matrix에 대해서 square root 구하기

[[      1     128    2187]
 [  16384   78125  279936]
 [ 823543 2097152 4782969]]
[[      1     128    2187]
 [  16384   78125  279936]
 [ 823543 2097152 4782969]]
[[ 1  4  9]
 [16 25 36]
 [49 64 81]]
[[1.         1.41421356 1.73205081]
 [2.         2.23606798 2.44948974]
 [2.64575131 2.82842712 3.        ]]


---

## broadcasting 연산
- 두 배열의 shape이 다르면 broadcasting 연산을 수행한다
- shape이 작은 쪽이 큰 쪽에 맞춰 확장한다
- 두 배열의 차원의 크기가 같거나, 하나가 1이면 브로드캐스팅 가능
- 그리고 크기가 1인 차원은 상대 배열의 해당 차원 크기와 다를 경우 자동으로 확장 가능하다
- shape이 다른 경우 마지막 축부터 차원이 동일한지 비교한다

In [39]:
result_arr = arr_a * np.array([[5,5,5],[5,5,5], [5,5,6]]) # (3,3)
result_arr = arr_a * np.array([5,5,5]) # (3,)
result_arr = arr_a * np.array([5]) # (1,)
result_arr = arr_a * np.array(5) # scalar 

print(result_arr)

[[ 5 10 15]
 [20 25 30]
 [35 40 45]]


In [ ]:
arr1 = np.array([[1,2,3],[4,5,6]]) # (2,3)
arr2 = np.array([5,10,100]) # (3,)
 
arr1 + arr2

array([[  6,  12, 103],
       [  9,  15, 106]])

In [41]:
arr1 = np.array([[1,2,3],[4,5,6]]) # (2,3)
arr2 = np.array([[100],[200]]) # (2,1)

arr1 + arr2

array([[101, 102, 103],
       [204, 205, 206]])

In [43]:
arr1 = np.array([1,2,3]) # (3,) => 차원 맞추면서 (1,3)
arr2 = np.array([[4],[5],[6]]) # (3,1)

arr1 + arr2 # (3,3)

array([[5, 6, 7],
       [6, 7, 8],
       [7, 8, 9]])

In [45]:
arr1 = np.array([[1,2,3],[4,5,6]]) # (2,3)
arr2 = np.array([1,2]) # (2,) -> (1,2) 

arr1 + arr2  # 무엇을 늘릴지 모를 때는 이렇게 error => ValueError

ValueError: operands could not be broadcast together with shapes (2,3) (2,) 

---

# 행렬 곱셈 (Matrix Multiplication)
- Dot Product (내적/ 점곱연산)
    - 두 행렬 A,B의 내적은 첫 번째 행렬 A의 행과 두 번째 행렬 B의 열 간의 곱셈을 수행한다
    - 첫 번째 행렬 A의 열의 수와 두 번째 행렬 B의 행의 수가 같아야 함
    - 연산 결과의 shape은 (A의 행 개수, B의 열 개수) 이다.

In [ ]:
arr1  = np.array([[1,2], [3,4]])
arr2 = np.array([[5,6], [7,8]])

print(arr1)
print(arr2)
print()
print(np.dot(arr1,arr2))
print(np.dot(arr1,arr2).shape) # (2,2)

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]

[[19 22]
 [43 50]]
(2, 2)


In [ ]:
arr3 = np.array([[1,2,3],[4,5,6]]) # (2,3)
arr4 = np.array([[7,8],[9,10],[11,12]]) # (3,2)

print(np.dot(arr3, arr4)) # (2,2)

# 2*2 matrix에서는 @ 기호로도 dot product 가능 => 사실 dot product 아니고 매트릭스 곱셈인 np.matnul()을 하는 것
print(arr3 @ arr4)

[[ 58  64]
 [139 154]]
[[ 58  64]
 [139 154]]


In [ ]:
## Transpose 해주기 (전치행렬)
# arr3 @ arr3은 안 됨. Why? shape가 (2,3) @ (2,3) 이니까 => 전치(transponse) 해줌

print(arr3.T, "\n")
print(arr3 @ arr3.T) # (2,3) @ (3,2)

# matnul로 해보기
print(np.matmul(arr3, arr3.T))

[[1 4]
 [2 5]
 [3 6]] 

[[14 32]
 [32 77]]


### 연산 함수 및 집계 함수

In [63]:
arr_negative = np.array([[-1, -2], [-100, -200]])
arr_float = np.array([[1.234, -5.678], [-7.89, 10.123]])
arr = np.arange(1, 7).reshape(2, 3)

In [65]:
# 올림 (현재 숫자보다 최소 정수 반환)
print(np.ceil(arr_float))
# 반올림
print(np.round(arr_float))
# 내림 (현재 숫자보다 작은 최대 정수 반환)
print(np.floor(arr_float))
# 버림 
print(np.trunc(arr_float))

[[ 2. -5.]
 [-7. 11.]]
[[ 1. -6.]
 [-8. 10.]]
[[ 1. -6.]
 [-8. 10.]]
[[ 1. -5.]
 [-7. 10.]]


In [66]:
# 절댓값
print(np.abs(arr_negative))

[[  1   2]
 [100 200]]


In [79]:
# 최대/최소값
arr = np.arange(1, 7).reshape(2, 3)

print(np.max(arr)) # MAX VALUE => np.max()
print(np.min(arr)) # MIN VALUE => np.min()

print(np.max(arr, axis =0))  # (2,3) shape에서 2 (2차원에서는 행 기준) => 가장 큰 값 가진 행 뽑음
print(np.min(arr, axis =1))  # (2,3) shape에서 3 (2차원에서는 열 기준) => 가장 큰 값 가진 열 뽑음

6
1
[4 5 6]
[1 4]


In [ ]:
# 합계
print(np.sum(arr))
 
print(arr.sum(axis=0)) # 행 방향으로 (밑으로) 더함.               
print(arr.sum(axis=1)) # 열 방향으로 (옆으로) 더함                   

21
[5 7 9]
[ 6 15]


In [ ]:
# 평균
print(np.mean(arr))
print(arr.mean())

print(arr.mean(axis=0)) # 행 방향으로 
print(arr.mean(axis=1))

3.5
3.5


In [ ]:
m