# ndarray 정렬

In [1]:
import numpy as np

## 1D Array Sort

In [8]:
arr = np.random.randint(1, 11, 10) # random 생성
arr

array([10,  1,  3,  1,  4,  9,  2,  7,  5,  5], dtype=int32)

In [ ]:
# np.sort(arr): 정렬된 ndarray를 '빈환'. 
# 원본 배열에 영향 X 
#  desc 설정 파라미터 없고, asc만 지원
np.sort(arr) 

array([ 1,  1,  2,  3,  4,  5,  5,  7,  9, 10], dtype=int32)

In [ ]:
print(arr)


[10  1  3  1  4  9  2  7  5  5]


In [11]:
# Descending order sort
np.sort(arr)[::-1]

array([10,  9,  7,  5,  5,  4,  3,  2,  1,  1], dtype=int32)

# 2D Array Sort

In [13]:
arr = np.random.randint(10, size=(3,4)) # 값 하나만 주면 end 값 => 0~9 안에서 랜덤
arr

array([[0, 4, 4, 6],
       [5, 8, 9, 5],
       [2, 4, 2, 8]], dtype=int32)

In [ ]:
np.sort(arr) # default로 axis=1 -> column방향 정렬

array([[0, 4, 4, 6],
       [5, 5, 8, 9],
       [2, 2, 4, 8]], dtype=int32)

In [ ]:
print(np.sort(arr, axis=0)) # 행row 방향 정렬
print(np.sort(arr, axis=1)) # 열col 방향 정렬

[[0 4 2 5]
 [2 4 4 6]
 [5 8 9 8]]
[[0 4 4 6]
 [5 5 8 9]
 [2 2 4 8]]


In [ ]:
print(np.sort(arr, axis=None)) # axis=None -> 축 무시 (행/열 구분 없이 정렬)
print(np.sort(arr, axis=None).shape) # (n,) -> 1D로 됨

[0 2 2 4 4 4 5 5 6 8 8 9]
(12,)


### np.argsort()
- 배열의 값을 정렬했을 때 각 값의 '원래 인덱스'를 반환
- = 정렬할 때 어떤 순서로 값을 배치해야 하는지 알려주는 인덱스
- = 배열의 값을 정리한 후, 정렬된 순서에 해당하는 인덱스를 반환

In [21]:
arr = np.array([100,400,200,300])
print(np.sort(arr))
print(np.argsort(arr))

[100 200 300 400]
[0 2 3 1]


In [30]:
# 자주 쓰는 경우 예시

blackpink = np.array(['제니', '로제', '리사', '지수'])
album_sales = np.array([900,870,780,1002])

# Sort index
desc_sorted_indices = np.argsort(album_sales)[::-1]

print("Sorted indices:", desc_sorted_indices)

# Sort blackpink based on those indices => Fancy indexing
print(blackpink[desc_sorted_indices] )

Sorted indices: [3 0 1 2]
['지수' '제니' '로제' '리사']


In [ ]:
# 2차원 배열 np.argsort()

arr = np.array([[2025, 7, 15], [14,41,30]])
print(np.argsort(arr)) #  default axis=1
print(np.argsort(arr, axis=1)) # column direction order
print(np.argsort(arr, axis=0)) # row direction order

[[1 2 0]
 [0 2 1]]
[[1 2 0]
 [0 2 1]]
[[1 0 0]
 [0 1 1]]
