# ndarray 병합 및 분할

In [2]:
import numpy as np

### ndarray 요소 추가 및 삭제
- ndarray는 고정 길이 배열이다 == 크기 변경이 불가하다 == 요소 추가 불가
- 하지만, np.append() & np.insert() 로 새로운 배열을 만드는 것은 가능

In [7]:
# np.append(원본배열, 삽입할 요소) -> 요소를 추가한 새로운 배열 반환
# np.insert(원본배열, 삽입할 위치 인덱스, 삽입할 요소)-> 요소를 추가한 새로운 배열 반환
arr = np.array([10,20,30])

arr1 = np.append(arr, 40)
arr2 = np.insert(arr, 1, 999) # 1번 index에 999 넣기

print(arr)
print(arr1)
print(arr2)

print(arr2 is arr) # 객체 비교 (== 쓰면 안 됨)

[10 20 30]
[10 20 30 40]
[ 10 999  20  30]
False


In [14]:
# 2차원 배열에서 insert()
arr2d = np.arange(1,13).reshape(3,4)
print(arr2d, '\n')

#np.append(arr2d, 100)
print(np.insert(arr2d, 1, 100), '\n')

# 파라미터 -> 원본배열, 삽입할 위치 인덱스, 삽입할 요소, axis (0/1)
print(np.insert(arr2d, 1, 100, axis=0), '\n')
print(np.insert(arr2d, 1, 100, axis=1))

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]] 

[  1 100   2   3   4   5   6   7   8   9  10  11  12] 

[[  1   2   3   4]
 [100 100 100 100]
 [  5   6   7   8]
 [  9  10  11  12]] 

[[  1 100   2   3   4]
 [  5 100   6   7   8]
 [  9 100  10  11  12]]


In [18]:
print(np.insert(arr2d, 1, 100, axis=1), '\n')
print(np.insert(arr2d, 1, [100], axis=1), '\n')
print(np.insert(arr2d, 1, [200, 300, 400], axis=1), '\n')
#print(np.insert(arr2d, 1, [200, 300, 400], axis=0)) # shape 안맞아서 에러
print(np.insert(arr2d, 1, [200, 300, 400, 500], axis=0)) 

[[  1 100   2   3   4]
 [  5 100   6   7   8]
 [  9 100  10  11  12]] 

[[  1 100   2   3   4]
 [  5 100   6   7   8]
 [  9 100  10  11  12]] 

[[  1 200   2   3   4]
 [  5 300   6   7   8]
 [  9 400  10  11  12]] 

[[  1   2   3   4]
 [200 300 400 500]
 [  5   6   7   8]
 [  9  10  11  12]]


In [19]:
# np.delet(원본배열, 삭제 요소 인덱스) -> 요소를 삭제한 새로운 배열 반환
arr = np.arange(1,15)
arr1 = np.delete(arr, 7)

print(arr)
print(arr1)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14]
[ 1  2  3  4  5  6  7  9 10 11 12 13 14]


In [20]:
arr2d = np.arange(1,13).reshape(3,4)

print(arr2d, '\n')
print(np.delete(arr2d, 1), '\n') # axis=None: 1차원 배열 변환 후 요소 삭제
print(np.delete(arr2d, 1, axis=0), '\n')
print(np.delete(arr2d, 1, axis=1), '\n')

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]] 

[ 1  3  4  5  6  7  8  9 10 11 12] 

[[ 1  2  3  4]
 [ 9 10 11 12]] 

[[ 1  3  4]
 [ 5  7  8]
 [ 9 11 12]] 



### ndarray 병합
- np.append() -> 기본 축 = None
- np.vstack()
- np.hstack()
- np.concatenate()-> append와 비슷하지만 튜플/리스트로 묶어서 전달 & 기본 축=0

In [21]:
arr1 = np.arange(1,13).reshape(3,4)
arr2 = np.arange(13,25).reshape(3,4) 
arr1, arr2

(array([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]]),
 array([[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]))

In [27]:
# np.append()
print(np.append(arr1, arr2), '\n') # axis=None
print(np.append(arr1, arr2, axis=0), '\n')
print(np.append(arr1, arr2, axis=1), '\n')

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24] 

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]] 

[[ 1  2  3  4 13 14 15 16]
 [ 5  6  7  8 17 18 19 20]
 [ 9 10 11 12 21 22 23 24]] 



In [28]:
# np.vstack(): axis=0 병합
# 병합 대상 ndarray를 튜플/리스트로 묶어서 전달해야 함
np.vstack((arr1,arr2))

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24]])

In [29]:
# np.hstack(): axis=1 병합
# 병합 대상 ndarray를 튜플/리스트로 묶어서 전달해야 함
np.hstack([arr1,arr2])

array([[ 1,  2,  3,  4, 13, 14, 15, 16],
       [ 5,  6,  7,  8, 17, 18, 19, 20],
       [ 9, 10, 11, 12, 21, 22, 23, 24]])

In [32]:
# np.concatenate()
# 병합 대상 ndarray를 튜플/리스트로 묶어서 전달해야 함
print(np.concatenate((arr1,arr2)),'\n') # axis 기본값 == 0
print(np.concatenate((arr1,arr2), axis=0),'\n')
print(np.concatenate((arr1,arr2), axis=1),'\n')
print(np.concatenate((arr1,arr2), axis=None),'\n')

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]] 

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]] 

[[ 1  2  3  4 13 14 15 16]
 [ 5  6  7  8 17 18 19 20]
 [ 9 10 11 12 21 22 23 24]] 

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24] 



### ndarray
- split()


In [37]:
arr = np.concatenate((arr1, arr2))
print(arr.shape)

# np.split(원본배열, 분할 개수, axiz)
print(np.split(arr,2), '\n') # default axis == 0
print(np.split(arr,2, axis=0), '\n') # default axis == 0
print(np.split(arr,2, axis=1), '\n')

(6, 4)
[array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]]), array([[13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24]])] 

[array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]]), array([[13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24]])] 

[array([[ 1,  2],
       [ 5,  6],
       [ 9, 10],
       [13, 14],
       [17, 18],
       [21, 22]]), array([[ 3,  4],
       [ 7,  8],
       [11, 12],
       [15, 16],
       [19, 20],
       [23, 24]])] 



In [42]:
n = 2

# 약수(factor)의 개수로만 분할 가능

# arr의 shape: (6,4)
print(np.split(arr,n,axis=0), '\n') # 행 기준 약수 -> 6행: 1,2,3,6 가능
print(np.split(arr,n,axis=1), '\n') # 열 기준 약수 -> 4열: 1,2,4 가능

[array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]]), array([[13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24]])] 

[array([[ 1,  2],
       [ 5,  6],
       [ 9, 10],
       [13, 14],
       [17, 18],
       [21, 22]]), array([[ 3,  4],
       [ 7,  8],
       [11, 12],
       [15, 16],
       [19, 20],
       [23, 24]])] 

