# ndarray 형태 변경

In [1]:
import numpy as np

## reshape()
- 요소의 개수가 맞는 shape으로 변경 가능

In [2]:
arr = np.arange(12)
print(arr.ndim, arr.shape)

1 (12,)


In [3]:
arr = arr.reshape(3, 4)
arr = arr.reshape(6, 2)
# arr = arr.reshape(2,7) -> 요소 개수가 달라서 불가능
arr = arr.reshape(2,2,3)
print(arr.ndim, arr.shape)
print(arr)

3 (2, 2, 3)
[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]


In [4]:
# reshape(-1): 1차원으로 처리
arr = arr.reshape(-1)
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [5]:
# reshape(a,b) -> a or b 하나가 -1: -1인 축은 자동 계산됨
arr = arr.reshape(4,-1)
arr = arr.reshape(-1,4)
print(arr)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


### np.ravel()
- 1차원 변환

In [6]:
arr = np.ravel(arr)
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


### np.expand_dims()
- 차원추가

In [7]:
arr_1d = np.arange(10)
print(arr_1d.shape, arr_1d)

#print(np.expand_dims(arr_1d)) 위치 인자 axis가 무조건 들어가야함
print(np.expand_dims(arr_1d, axis = 0))
print(np.expand_dims(arr_1d, axis = 0).shape)
print()
print(np.expand_dims(arr_1d, axis = 1))
print(np.expand_dims(arr_1d, axis = 1).shape, np.expand_dims(arr_1d, axis = 1).ndim)

(10,) [0 1 2 3 4 5 6 7 8 9]
[[0 1 2 3 4 5 6 7 8 9]]
(1, 10)

[[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]
(10, 1) 2


In [8]:
arr_2d = np.array([[1,2], [3,4]])
print(arr_2d.shape, '\n', arr_2d)

print()
print(np.expand_dims(arr_2d, axis = 0))
print(np.expand_dims(arr_2d, axis = 0).shape, np.expand_dims(arr_2d, axis = 0).ndim)
print()
print(np.expand_dims(arr_2d, axis = 1))
print(np.expand_dims(arr_2d, axis = 1).shape, np.expand_dims(arr_2d, axis = 1).ndim)
print()
print(np.expand_dims(arr_2d, axis = 2))
print(np.expand_dims(arr_2d, axis = 2).shape, np.expand_dims(arr_2d, axis = 2).ndim)

(2, 2) 
 [[1 2]
 [3 4]]

[[[1 2]
  [3 4]]]
(1, 2, 2) 3

[[[1 2]]

 [[3 4]]]
(2, 1, 2) 3

[[[1]
  [2]]

 [[3]
  [4]]]
(2, 2, 1) 3


### np.squeeze()
- 차원의 값(=해당 차원의 요소 개수)이 1일 때, 차원 제거

In [11]:
arr = np.array([[1,2]])
print(arr.shape)

arr2 = np.squeeze(arr)
arr2 = np.squeeze(arr, axis=0)
#arr2 = np.squeeze(arr, axis=1) # 이 축의 요소 개수는 2개 (column)이라서 불가

print(arr2.shape)

(1, 2)
(2,)
