In [9]:
import numpy as np

# 배열 생성하세요

In [14]:
# 1. 크기가 4x3인 모든 값이 0인 배열
zeroes_arr = np.zeros((4,3), dtype=int)
zeroes_arr

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [17]:
# 2. 크기가 3x3인 모든 값이 1인 배열
ones_arr = np.ones((3,3), dtype=int)
ones_arr

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [18]:
# 3. 0에서 20까지 5씩 증가하는 값으로 구성된 배열
arith_arr1 = np.arange(0,21,5)
arith_arr1

array([ 0,  5, 10, 15, 20])

In [19]:
# 4. 0과 1 사이의 4개의 등간격 값을 가진 배열
arith_arr2 = np.linspace(0,1,4)
arith_arr2

array([0.        , 0.33333333, 0.66666667, 1.        ])

In [ ]:
# 5. 크기가 2x2인 정규 분포로 구성된 배열

arr_norm = np.random.normal(loc=0.0, scale=1.0, size=(2, 2))
"""
loc=0.0: mean of the distribution (mu)

scale=1.0: standard deviation (sigma)

size=(2, 2): shape of the output array 
"""
arr_norm

array([[ 1.34998256,  0.13048519],
       [ 0.11932465, -0.30920604]])

# 아래 배열에서 인덱싱과 슬라이싱을 사용하여 다음 작업을 수행하세요.

In [21]:
arr = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])

In [22]:
# 1. 배열 arr에서 2번째 행, 3번째 열의 값을 출력
print(arr[1,2])

60


In [24]:
# 2. 배열 arr에서 1번째 열만 추출
print(arr[:, 0:1])

[[10]
 [40]
 [70]]


In [25]:
# 3. 배열 arr에서 첫 번째 행부터 두 번째 행까지 선택하고, 0번째와 1번째 열만 추출
print(arr[:2, :2])

[[10 20]
 [40 50]]


# [실습 2] 팬시 인덱싱과 불리언 인덱싱

In [26]:
arr = np.array([10, 20, 30, 40, 50, 60, 70])

In [28]:
# 1. 팬시 인덱싱을 사용하여 배열의 0번째, 2번째, 4번째 요소를 출력
indices = [0,2,4]
print(arr[indices])

[10 30 50]


In [29]:
# 2. 배열의 값 중 50보다 큰 값만 추출
print(arr[arr > 50])

[60 70]


# [실습 3] 제품 판매 데이터 분석
어느 마트에서 판매되는 제품들의 월별 매출량이 아래와 같이 주어졌습니다. 각각의 행은 제품을 나타내고, 열은 각 월의 판매량을 나타냅니다.

In [72]:
sales = np.array([[120, 150, 100],
                  [80, 90, 110],
                  [200, 180, 220],
                  [50, 45, 70],
                  [300, 320, 310]])

In [106]:
 # 1. 월별 판매량이 200개 이상인 제품의 판매량을 선택하라.

# 모든 월의 판매량이 200이 넘는 제품 
print(sales[np.all(sales >= 200, axis=1), : ]) 

#  200 이상인 판매량
print(sales[sales>=200])

# 천체 값이 200이상? False
print(np.all(sales >= 200)) 


[[300 320 310]]
[200 220 300 320 310]
False


In [97]:
# 2. 3월(세 번째 열)의 판매량이 100개 이하인 제품의 1월과 2월 판매량을 추출하라.

# 방법 1
match_condition = sales[:, 2] <= 100 # 1D boolean array
print(sales[match_condition, :2], '\n')
print('Samness test:\n', sales[(sales[:,2]<=100), :2]) # same

print()

# 방법 2 (가독성 bad)
mask = sales[:, 2] <= 100 # 1D array for 3rd colum boolean => [ True False False  True False] 
print(sales[np.any([mask], axis=0), :2]) # axis 0: column, axis 1; row


[[120 150]
 [ 50  45]] 

Samness test:
 [[120 150]
 [ 50  45]]

[[120 150]
 [ 50  45]]


In [ ]:
# 3. 2월(두 번째 열)의 판매량이 150개 이상인 제품들의 전체 월별 판매량을 출력하라.
match_condition = sales[:, 1] >= 150 
print(sales[match_condition]) # = sales[match_condition, :]

[[120 150 100]
 [200 180 220]
 [300 320 310]]
