In [1]:
import numpy as np

다음과 같은 과일 판매량 데이터가 있습니다. 각 과일의 1분기와 2분기 판매량이 주어졌을 때, NumPy 배열을 사용하여 아래 문제를 해결하세요.

In [10]:
# 사과, 배, 오렌지, 바나나
fruit_sales = np.array([[200, 340, 150, 400], [220, 300, 180, 420]])

In [14]:
# 1. 1분기와 2분기의 과일별 총 판매량을 구하세요.
print("Q1 Net:", fruit_sales.sum(axis=1)[0])
print("Q2 Net:", fruit_sales.sum(axis=1)[1])

Q1 Net: 1090
Q2 Net: 1120


In [16]:
# 2. 과일별 평균 판매량을 구하세요.
print(fruit_sales.mean(axis=0))

[210. 320. 165. 410.]


다음 두 배열을 사용하여 각각의 요소별로 덧셈, 뺄셈, 곱셈, 나눗셈을 수행하세요.

In [17]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

In [19]:
print(arr1+arr2)
print(arr1-arr2)
print(arr1*arr2)
print(arr1/arr2)

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]


# [실습 3] 브로드캐스팅
아래의 2차원 배열과 1차원 배열을 브로드캐스팅하여 더하세요.

In [21]:
arr2d = np.array([[1, 2, 3], [4, 5, 6]]) # (2,3)
arr1d = np.array([10, 20, 30]) # (3,) -> (1,3)

print(arr2d + arr1d)

[[11 22 33]
 [14 25 36]]


# [실습 4] 비교 연산 및 집계 함수 사용

In [22]:
arr = np.array([10, 20, 30, 40, 50])

In [24]:
# 1. 배열에서 20보다 큰 값을 찾아 출력하세요.
print(arr[arr>20])

[30 40 50]


In [26]:
# 2. 배열의 합계, 최대값, 최소값, 평균을 계산하세요.
print(arr.sum())
print(arr.max())
print(arr.min())
print(arr.mean())

150
50
10
30.0
