다음은 5개 지점에서 판매된 과일에 대한 월별 판매량 데이터입니다. 이 데이터는 각 지점의 판매량을 월별로 나타내며, 각 지점에서 판매된 사과, 바나나, 오렌지의 판매량이 기록되어 있습니다. 이 데이터를 사용하여 여러 가지 통계적 분석과 배열 조작을 수행하세요.

In [2]:
import numpy as np

# 5개 지점의 월별 사과, 바나나, 오렌지 판매량 (5x3x6 배열)
# 5개의 지점, 3개의 과일(사과, 바나나, 오렌지), 6개월치 데이터
sales_data = np.array([
    # 지점 1
    [[120, 150, 200, 230, 180, 210],  # 사과 판매량
     [100, 140, 170, 190, 160, 180],  # 바나나 판매량
     [90, 120, 160, 140, 130, 150]],  # 오렌지 판매량

    # 지점 2
    [[80, 90, 110, 140, 130, 120],
     [60, 70, 90, 100, 110, 95],
     [50, 80, 100, 110, 90, 85]],

    # 지점 3
    [[130, 140, 160, 180, 170, 190],
     [110, 120, 130, 150, 140, 160],
     [100, 110, 120, 130, 120, 140]],

    # 지점 4
    [[100, 130, 150, 170, 160, 180],
     [90, 100, 110, 120, 130, 125],
     [80, 110, 140, 130, 120, 110]],

    # 지점 5
    [[90, 110, 130, 140, 120, 130],
     [70, 85, 100, 110, 105, 95],
     [60, 90, 110, 100, 90, 95]]
])

1. 각 지점에서 6개월 동안 판매된 사과, 바나나, 오렌지의 월별 평균 판매량을 계산하세요.

In [ ]:
""" 출력값:
array([[181.66666667, 156.66666667, 131.66666667],
       [111.66666667,  87.5       ,  85.83333333],
       [161.66666667, 135.        , 120.        ],
       [148.33333333, 112.5       , 115.        ],
       [120.        ,  94.16666667,  90.83333333]])
"""
fruit_sales_avg = np.mean(sales_data, axis = 2)
print(fruit_sales_avg)

[[181.66666667 156.66666667 131.66666667]
 [111.66666667  87.5         85.83333333]
 [161.66666667 135.         120.        ]
 [148.33333333 112.5        115.        ]
 [120.          94.16666667  90.83333333]]


2. 각 월마다 전체 지점에서 가장 많이 판매된 과일을 찾아 판매량과 과일명을 출력하세요.

In [12]:
"""출력값:
[[520 620 750 860 760 830]
 [430 515 600 670 645 655]
 [380 510 630 610 550 580]]
 
[520 620 750 860 760 830]

[0 0 0 0 0 0] 
"""

fruits = {0:"사과", 1:"바나나", 2:"오렌지"}

# 1. 전체지점 월별 과일당 총 판매량
sum_fruit_monthly = np.sum(sales_data, axis=0)
print(sum_fruit_monthly, '\n')

# 2. 각 월 별 최고 판매량 
max_sale_monthly = np.max(sum_fruit_monthly, axis = 0)
print(max_sale_monthly, '\n')

# 3. 최고 판매된 과일 index
#np.argsort(sum_fruit_monthly, axis=0)
max_sales_fruit_idx = np.min(np.argsort(sum_fruit_monthly, axis=0), axis=0)
print(max_sales_fruit_idx, '\n')

for i,idx in enumerate(max_sales_fruit_idx):
    print(fruits[idx], max_sale_monthly[i])


[[520 620 750 860 760 830]
 [430 515 600 670 645 655]
 [380 510 630 610 550 580]] 

[520 620 750 860 760 830] 

[0 0 0 0 0 0] 

사과 520
사과 620
사과 750
사과 860
사과 760
사과 830


In [13]:
# 강사님 답
monthy_total_sales = np.sum(sales_data, axis=0)
print(monthy_total_sales, '\n')

monthly_max_sales = np.max(monthy_total_sales, axis=0)
print(monthly_max_sales, '\n')

max_index = np.argmax(monthy_total_sales, axis=0)

for idx in max_index:
    print(['사과','바나나','오렌지'][idx])

[[520 620 750 860 760 830]
 [430 515 600 670 645 655]
 [380 510 630 610 550 580]] 

[520 620 750 860 760 830] 

사과
사과
사과
사과
사과
사과


3. 6개월 동안 전체 지점에서 가장 많이 판매된 과일의 총량을 과일별로 구하세요. 어떤 과일이 가장 많이 판매되었는지 확인하세요.

In [81]:
"""출력값:
[4340 3515 3260]
0                -> index로 출력되어도 되고 리스트를 만들어 이름으로 출력되도록 해도 됨 
"""

# 월별 각각 과일 판매량 (지점 다 합침)
#print(np.sum(sales_data, axis=0))

# 과일별 전체 판매 (지점 & 월 다 합침) 
print(np.sum(np.sum(sales_data, axis=0), axis=1))

# 과일별 전체 판매 (지점 & 월 다 합침) 과일별 인덱스
#print(np.argsort(np.sum(np.sum(sales_data, axis=0), axis=1)))

# 제일 많이 팔린 과일 인덱스
print(np.min(np.argsort(np.sum(np.sum(sales_data, axis=0), axis=1))))

[4340 3515 3260]
0


In [20]:
# 강사님 답
total_sales_per_fruit = np.sum(sales_data, axis=(0,2))
print(total_sales_per_fruit, '\n')



most_sold_fruit_idx = np.argmax(total_sales_per_fruit, axis=0)
print(most_sold_fruit_idx)
print(['사과','바나나','오렌지'][most_sold_fruit_idx])

[4340 3515 3260] 

0
사과


4. 각 지점에서 판매량이 150개 이상인 (200 이상인듯?) 데이터를 추출하고 그에 해당하는 지점과 과일을 출력하세요.

In [4]:
""" 출력값
[150 200 230 180 210 170 190 160 180 160 150 160 180 170 190 150 160 150
 170 160 180]
(array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3],
      dtype=int64), array([0, 0, 0, 0, 0, 1, 1, 1, 1, 2, 2, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0],
      dtype=int64), array([1, 2, 3, 4, 5, 2, 3, 4, 5, 2, 5, 2, 3, 4, 5, 3, 5, 2, 3, 4, 5],
      dtype=int64))
1 지점, 사과 과일, 2월
1 지점, 사과 과일, 3월
1 지점, 사과 과일, 4월
1 지점, 사과 과일, 5월
1 지점, 사과 과일, 6월
1 지점, 바나나 과일, 3월
1 지점, 바나나 과일, 4월
1 지점, 바나나 과일, 5월
1 지점, 바나나 과일, 6월
1 지점, 오렌지 과일, 3월
1 지점, 오렌지 과일, 6월
3 지점, 사과 과일, 3월
3 지점, 사과 과일, 4월
3 지점, 사과 과일, 5월
3 지점, 사과 과일, 6월
3 지점, 바나나 과일, 4월
3 지점, 바나나 과일, 6월
4 지점, 사과 과일, 3월
4 지점, 사과 과일, 4월
4 지점, 사과 과일, 5월
4 지점, 사과 과일, 6월
"""

# 과일 이름
fruit_names = np.array(['사과', '바나나', '오렌지'])
branch_names = np.array(['지점 1', '지점 2', '지점 3', '지점 4', '지점 5'])
month = {0: "1월", 1:"2월", 2:"3월", 3:"4월", 4:"5월", 5:"6월"}

# 판매량 150 넘는 데이터
print(sales_data[sales_data >= 150], '\n')



# 판매량 150 넘는 데이터 존재하는 (지점, 과일, 월)
print(np.where(sales_data>=150))

# 판매량 150 넘는 데이터 각각의 인덱스
branches, fruits, months = np.where(sales_data>=150)

print()
for b, f, m in zip(branches, fruits, months):
    print(f"{branch_names[b]} 지점, {fruit_names[f]} 과일, {month[m]}")
    print(b,f,m+1)


[150 200 230 180 210 170 190 160 180 160 150 160 180 170 190 150 160 150
 170 160 180] 

(array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3]), array([0, 0, 0, 0, 0, 1, 1, 1, 1, 2, 2, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0]), array([1, 2, 3, 4, 5, 2, 3, 4, 5, 2, 5, 2, 3, 4, 5, 3, 5, 2, 3, 4, 5]))

지점 1 지점, 사과 과일, 2월
0 0 2
지점 1 지점, 사과 과일, 3월
0 0 3
지점 1 지점, 사과 과일, 4월
0 0 4
지점 1 지점, 사과 과일, 5월
0 0 5
지점 1 지점, 사과 과일, 6월
0 0 6
지점 1 지점, 바나나 과일, 3월
0 1 3
지점 1 지점, 바나나 과일, 4월
0 1 4
지점 1 지점, 바나나 과일, 5월
0 1 5
지점 1 지점, 바나나 과일, 6월
0 1 6
지점 1 지점, 오렌지 과일, 3월
0 2 3
지점 1 지점, 오렌지 과일, 6월
0 2 6
지점 3 지점, 사과 과일, 3월
2 0 3
지점 3 지점, 사과 과일, 4월
2 0 4
지점 3 지점, 사과 과일, 5월
2 0 5
지점 3 지점, 사과 과일, 6월
2 0 6
지점 3 지점, 바나나 과일, 4월
2 1 4
지점 3 지점, 바나나 과일, 6월
2 1 6
지점 4 지점, 사과 과일, 3월
3 0 3
지점 4 지점, 사과 과일, 4월
3 0 4
지점 4 지점, 사과 과일, 5월
3 0 5
지점 4 지점, 사과 과일, 6월
3 0 6


In [31]:
# 강사님 답
required_sales_data = sales_data[sales_data>=150]
print(required_sales_data, '\n')

#branches, fruits, months = np.where(sales_data>=150) # 각각에 담어주기
over_150_data_indices = np.where(sales_data >= 150)
print(over_150_data_indices[0]) # 지점
print(over_150_data_indices[1]) # 과일
print(over_150_data_indices[2]) # 월

print()

for i in range(len(over_150_data_indices[0])):
    spot = over_150_data_indices[0][i] + 1
    fruit_idx = over_150_data_indices[1][i]
    fruit = ['사과', '바나나', '오렌지'][fruit_idx]
    month = over_150_data_indices[2][i] + 1
    print(f"지점: {spot}, 과일: {fruit}, 월: {month}")



[150 200 230 180 210 170 190 160 180 160 150 160 180 170 190 150 160 150
 170 160 180] 

[0 0 0 0 0 0 0 0 0 0 0 2 2 2 2 2 2 3 3 3 3]
[0 0 0 0 0 1 1 1 1 2 2 0 0 0 0 1 1 0 0 0 0]
[1 2 3 4 5 2 3 4 5 2 5 2 3 4 5 3 5 2 3 4 5]

지점: 1, 과일: 사과, 월: 2
지점: 1, 과일: 사과, 월: 3
지점: 1, 과일: 사과, 월: 4
지점: 1, 과일: 사과, 월: 5
지점: 1, 과일: 사과, 월: 6
지점: 1, 과일: 바나나, 월: 3
지점: 1, 과일: 바나나, 월: 4
지점: 1, 과일: 바나나, 월: 5
지점: 1, 과일: 바나나, 월: 6
지점: 1, 과일: 오렌지, 월: 3
지점: 1, 과일: 오렌지, 월: 6
지점: 3, 과일: 사과, 월: 3
지점: 3, 과일: 사과, 월: 4
지점: 3, 과일: 사과, 월: 5
지점: 3, 과일: 사과, 월: 6
지점: 3, 과일: 바나나, 월: 4
지점: 3, 과일: 바나나, 월: 6
지점: 4, 과일: 사과, 월: 3
지점: 4, 과일: 사과, 월: 4
지점: 4, 과일: 사과, 월: 5
지점: 4, 과일: 사과, 월: 6


[[[False False  True  True  True  True]
  [False False  True  True  True  True]
  [False False  True False False False]]

 [[False False False False False False]
  [False False False False False False]
  [False False False False False False]]

 [[False False  True  True  True  True]
  [False False False False False  True]
  [False False False False False False]]

 [[False False False  True  True  True]
  [False False False False False False]
  [False False False False False False]]

 [[False False False False False False]
  [False False False False False False]
  [False False False False False False]]]
